2015-05-10 14:39:14.291 [IPEngineApp] Loading url_file u'/Users/robert/.ipython/profile_basic/security/ipcontroller-engine.json'
2015-05-10 14:39:14.294 [IPEngineApp] Registering with controller at tcp://127.0.0.1:49580
2015-05-10 14:39:14.360 [IPEngineApp] Starting to monitor the heartbeat signal from the hub every 3010 ms.
2015-05-10 14:39:14.363 [IPEngineApp] Using existing profile dir: u'/Users/robert/.ipython/profile_basic'
2015-05-10 14:39:14.364 [IPEngineApp] Completed registration with id 3
2015-05-11 00:06:27.842 [IPEngineApp] Exception in apply request:
[0;31m---------------------------------------------------------------------------[0m
[0;31mIOError[0m                                   Traceback (most recent call last)
[0;32m<string>[0m in [0;36m<module>[0;34m()[0m

[0;32m<ipython-input-253-f0f37a738a9d>[0m in [0;36mfile_process[0;34m(f)[0m

[0;32m<ipython-input-253-f0f37a738a9d>[0m in [0;36mget_meta_data[0;34m(filename)[0m

[0;32m<ipython-input-253-f0f37a738a9d>[0m in [0;36mget_data_file[0;34m(filename, report)[0m

[0;31mIOError[0m: [Errno 2] No such file or directory: '~/DropBox/Investigations/Signal_Quality_Assessment/data/ASH_2015_01_02_15_46.csv'
2015-05-11 00:08:27.124 [IPEngineApp] Exception in apply request:
[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<string>[0m in [0;36m<module>[0;34m()[0m

[0;32m<ipython-input-255-242664e68b5f>[0m in [0;36mfile_process[0;34m(f)[0m

[0;31mNameError[0m: global name 'display' is not defined
2015-05-11 00:11:17.395 [IPEngineApp] WARNING | No heartbeat in the last 3010 ms (1 time(s) in a row).
2015-05-11 00:31:18.385 [IPEngineApp] WARNING | No heartbeat in the last 3010 ms (1 time(s) in a row).
